ROW_NUM = 25
COL_NUM = 50

NUM_OF_MINES = 10
NUM_OF_GRASS = 20

EMPTY = 0
FLAG = 1
MINE = 2
GRASS = 3
MINE_SHADOW = 4
GRASS_SHADOW = 5
FLAG_SHADOW = 6

BLUE = (30,144,255)
BLACK = (0, 0, 0)

BACKGROUND_COLOR = BLUE

SQUARE_LEN = 20

WINDOW_HEIGHT = ROW_NUM * SQUARE_LEN
WINDOW_WIDTH = COL_NUM * SQUARE_LEN

FONT_NAME = 'Arial'
FONT_SIZE = 50
FONT_COLOR = (0, 0, 0)

BUBBLES_SIZE = (2, 2)
PLASTIC_BAG_SIZE = (2, 3)
TURTLE_SIZE = (5, 5)
SEAWEED_SIZE = (5, 6)


IMG_PLASTIC_BAG = 'PLASTICBAG.png'
IMG_DEATH = 'rip.png'
IMG_TURTLE = 'turtle.png'
IMG_SEAWEED = 'seaweed.png'
IMG_BUBBLES = 'bubbles.png'